### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/homedecor_modpack#10]
Recipes
building_blocks:woodglass recipe could be shapeless and use group:wood instead of default:wood
most lamp crafts from homedecor_lighting use iron_lump but I think it would make more sense to use iron_ingot instead since it is mostly forged metal parts of the item; and also on a multiplayer server its often easier to buy iron ingots than iron lump because everyone cook them as soon as they mine them.
wardrobe, desk, filing_cabinet and table use default:wood but group:wood would be better

**Comment by wsor4035** [comment]
Vanessa Dannenberg @VanessaE · 1 year ago
Maintainer
Pull requests welcome as always, with one caveat: I chose iron lumps for some lamps because to my mind, things that look like wrought iron should be made from actual iron rather than steel, even if such things are usually just steel altered or painted to look that way these days. Or at least, that's how I remember it. 😄

Hell, even my soldering iron's tips are plated with iron, not steel (I learned recently that this is common practice now). So it seems reasonable to use iron.

Now for those lamps that don't look like wrought iron, then yeah I'll accept steel in their recipes, as long as the recipes are unique enough not conflict with anything.

Please do any such testing by making your changes and then plugging them into Dreambuilder in place of the home decor mods there. That way you get a nice, large crafting profile, easy to look for conflicts.

Edited by Vanessa Dannenberg 1 year ago

**Comment by wsor4035** [comment]
Louis Royer @lroyer · 1 year ago
Author
Contributor
For this kind of changes, I prefer to submit an issue first; just to approve/reject the concept.

For the lamps, there is only two of them using iron lump (homedecor:oil_lamp_tabletop, and homedecor:wall_lamp_on) but if I change the craft of the first one, there will be a conflict with the homedecor:oil_lamp craft). Other crafts seems to use iron lump in the modpack, but some custom materials would fit better than iron ingot in my opinion. So it is likely I will not submit any change related to iron lump at all.

For the other crafts, I will check for conflicts into dreambuilder (I will also check for replacement of default:stick by group:stick).

Independently of the testing part, where do you prefer to have PR submitted: on homedecor modpack, on dreambuilder modpack, or on both? I guess it's on this repo, and that dreambuilder is basically a mirror regrouping all mods (but are you maintaining all these mods up-to-date entirely by hand? I haven't see any git submodule stuff or custom update script in the repo), but I want to be sure.

**Comment by wsor4035** [comment]
Peter Nerlich @PeterNerlich · 11 months ago
Contributor
It also seems like building_blocks:fakegrass uses default:leaves, making it uncraftable if moretrees is enabled (I think this is the case, maybe not). It would make sense to replace it with group:leaves which should always exist since it's builtin, if I saw that correctly.

**Comment by wsor4035** [comment]
@louisroyer is there any interest in submitting a PR for this, or should it be closed?

**Comment by louisroyer** [comment]
Sorry, I don't have time to contribute to mods anymore. I will add this to my todolist, and will submit a PR, but don't expect it until years… Feel free to close the issue until then; I can always re-open it if required.
