### ISSUE TITLE
Looks cool but with a problem

### ISSUE THREAD

**Issue by MidnightPhantom** [mt-mods/homedecor_modpack#29]
Your mod is nice but has many problems with it.
Firstly it has round furniture which you can keep more pixelated.
Secondly, homedecor_seating is nearly useless as you cannot sit on much of the stuff.
Thirdly your modpack does have some uncraftable items.

**Comment by S-S-X** [comment]
Break down to separate issues:

> it has round furniture which you can keep more pixelated.

I think this is simply intended homedecor style? Probably wont be reworked at least not anytime soon.

> homedecor_seating is nearly useless as you cannot sit on much of the stuff.

- [ ] create another issue with list of technical item names that should be fixed.
This probably requires some manual work to decide what items should be suitable for sitting.

> modpack does have some uncraftable items.

- [ ] create another issue with list of technical item names that should be fixed.
Should be able to collect uncraftable items with some script like some debugging mod or we //lua command.

**Comment by wsor4035** [comment]
basically what s-s-x said, additionally if you make a list of the uncraftable items, ill fix it in https://github.com/mt-mods/homedecor_modpack/pull/28

**Comment by wsor4035** [comment]
closing, as per s-s-x comment, anything of value in this issue needs a new one/be expounded
