### ISSUE TITLE
unbalanced parentheses (extranous '(') while ...

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/homedecor_modpack#30]
when get an homedecor_glowlight_base.png in view

that earning comes up:
unbalanced parentheses (extranous '(') while generating texture "(homedecor_glowlight_base.png"
as ERROR[Main]: generateImage():

looking the code, wondering that the last option in {} also get a, ... but no idea so far what it mean.

https://github.com/mt-mods/homedecor_modpack/blob/master/homedecor_lighting/init.lua#L227

good luck.

**Comment by wsor4035** [comment]
cant verify on 5.5 with the default glowlight nodes at least

**Comment by wsor4035** [comment]
closing as can not verify, as well as @OgelGames and the code looks right to both of us. if someone has this issue, please comment with how to reproduce it here or in a new issue
