### ISSUE TITLE
list of missing crafting recipes

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/homedecor_modpack#39]
- [ ] homedecor:chains
- [ ] homedecor:dvd_cd_cabinet
- [x] homedecor:dvd_player
- [x] homedecor:glass_table_large_square
- [ ] homedecor:rope_light_on_ceiling_off
- [ ] homedecor:rope_light_on_floor_off
- [ ] homedecor:shrubbery_large_green
- [x] homedecor:standing_lamp_14
- [x] homedecor:table_lamp_14
- [ ] homedecor:wardrobe
- [x] homedecor:wood_table_large_square

**Comment by BuckarooBanzay** [comment]
Related: https://content.minetest.net/threads/2952/

```
The mod itself is amazing. But there are also big drawbacks.
For example, there are no recipes for crafting a few items, although older releases
used to have them - grandfather clock, rope lighting, table lamp, stading lamp,
cutlery set, cup of beer, hueg box, dvd_player and wardrobe.
Also, in the new releases of this mod, for some reason, there is no gold coin
with which you can get coca cola from a soda machine. There was also an issue with 
ot being able to sleep in the new beds, but that's been fixed and I'm glad about that.

VanessaE, if you're reading this, please add the crafting recipes for all the items I've listed.
Thanks in advance! (;
```

**Comment by Niklp09** [comment]
When I find old recipes, I add them again

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/182518116-c8e6f9b5-810f-485c-b3ce-5b48797ce82c.png)
checked one off the list as its actually fine

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/182518220-d63085ac-8e5c-4dd9-8775-7eb5f6eedd38.png)
and another

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/182519305-70d9ddc6-ab0d-42fb-9d9e-a1405316349d.png)
checked off 14 as its not in inv and 11 should be crafted

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/182519395-10db168c-3985-44f6-a7e0-e2fd6616077d.png)
same deal on the table lamp

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/182519762-df4dc56c-bd5a-4418-a675-963c9bc39a0e.png)
another one checked off
