### ISSUE TITLE
A list of chairs that I can't sit in

### ISSUE THREAD

**Issue by Lazerbeak12345** [mt-mods/homedecor_modpack#42]
As per request in #29, (and since this effects me) I'm making a list of all of the chairs I can find that I can't sit in upon a simple playtest.

- [ ] `homedecor:deckchair`
- [ ] `homedecor:kitchen_chair_padded`
- [ ] `homedecor:kitchen_chair_wood`
- [x] `homedecor:armchair` (not to be confused with `lrfurn:armchair` - a separate item)
- [ ] `homedecor:office_chair_basic`
- [ ] `homedecor:office_chair_upscale`
- [ ] `homedecor:deckchair_striped_blue`

This list might not be exhaustive. It's only the ones I found.

This list is _not_ including chairs like the ones in #31 where clicking on the chair does _something_ - regardless of what it's actually doing.

List from homedecor at commit: 3ba59dc2d5d14c74bc2664eebcbff764f96f6f26

**Comment by wsor4035** [comment]
iirc without looking at the code rn:
probably easiest to move sitting logic to homedecor common from lrfurn, and then point lrfurns func at it for backwards compat. this way any of the homedecor_* mods could call the existing sitting logic.

always best to test with latest, not that it should make a difference in this case

**Comment by wsor4035** [comment]
checked off `homedecor:armchair` as it works perfectly fine
