### ISSUE TITLE
Unable to Pick Up Items Once Placed

### ISSUE THREAD

**Issue by atomdmac** [mt-mods/homedecor_modpack#49]
I'm using this mod with Mineclone 5.  One I place a crafted item in the world, I'm unable to break it or pick it up.  I've tried with and without tools.  There don't appear to be any errors being generated but let me know if there's any other information I can provide.

**Comment by wsor4035** [comment]
probably doesnt have the right groups for the hand/tools in survival. iirc it works in creative. ill look into this

**Comment by wsor4035** [comment]
@atomdmac just for replicating purposes, which items where you using? ~~so i have this information when i work on it~~

**Comment by atomdmac** [comment]
@wsor4035 this was happening with every item from this mod pack for me.

**Comment by wsor4035** [comment]
thanks. what i expected. just want to check

**Comment by atomdmac** [comment]
I noticed today that I'm able to pick up items without an issue as long as `Creative Mode` is enabled.  If it's _disabled_, I'm unable to pick up `homedecor` items.

**Comment by atomdmac** [comment]
I'm also able to pick up items without issue if I use the mod in the `minetest` game.  It only seems to be an issue when used with `mineclone5` (though I have not tested other games).

**Comment by wsor4035** [comment]
I'm aware, planning to look at this later today

**Comment by atomdmac** [comment]
@wsor4035 Thanks again for taking a look at this!  

Unfortunately, I'm still seeing the problem even when I have no other mods installed (aside from the ones requires by `MineClone5` and `homedecor`.  I'll take a closer look when I have a chance and add any other details here.

**Comment by wsor4035** [comment]
ill look into this. can you try mineclone2 as a comparison?

**Comment by atomdmac** [comment]
I just tried it out with `mineclone2` and the issue appears to be present there as well.

**Comment by wsor4035** [comment]
thats odd, considering i tested it there myself. what commit of homedecor(you did update right? just checking) and what commit of mineclone2 are you on?

**Comment by atomdmac** [comment]
`homedecor`: `0384943a0ad7873c1ecdcd56ed7fca81294e3571`
`mineclone2`: `588425df7365a775e39e5606bc77378072c6c213`

**Comment by wsor4035** [comment]
tried out `homedecor:bathroom_tiles_dark` on the exact commit with a diamond pick axe and it dug fine. basic materials and unified dyes are the only other two mods on top of mineclone2 (mte 5.6) that are enabled (used as deps). if you try and dig this (randomly selected) test case, still no luck?

**Comment by wsor4035** [comment]
dunno if our time zones would even line up, but do you have a discord/matrix/irc account we could message back and forth sometime to try and resolve the issue? your should be able to find me on the minetest channels/servers on any of those platforms if that works for you. (i go by wsor, sometimes with an extra pre or post suffix)

**Comment by atomdmac** [comment]
Using the `homedecor:bathroom_tiles_dark`, I was able to dig it up successfully using the diamond pickaxe.  

Up until this point, I've been using the `lrfurn:longsofa` item as my test case.  I tried that out as well (attempting to dig it up with the diamond pickaxe) but had no luck.

**Comment by wsor4035** [comment]
oh, i know what the issue is. your using one of the handful of not registered through homedecor common nodes. ill have to patch those up

**Comment by wsor4035** [comment]
pending atomdmac being all good, this should be good to close

**Comment by atomdmac** [comment]
Works now - this can be closed!
