### ISSUE TITLE
Itemframes error at pt_BR

### ISSUE THREAD

**Issue by luizsabino** [mt-mods/homedecor_modpack#50]
I found a error when I use the itemframes, my language is pt_BR
![image](https://user-images.githubusercontent.com/16266830/220166863-43ffc86e-a3f7-4099-a882-fc83171dab76.png)

**Comment by x2048** [comment]
The reason is that pt and pt_BR tr files for itemframes have @l instead of @1 in the translated string

**Comment by luizsabino** [comment]
Can I to fix in init.lua?

**Comment by x2048** [comment]
No, the files are in locale subfolder. For example, https://github.com/mt-mods/homedecor_modpack/blob/master/itemframes/locale/itemframes.pt.tr

**Comment by luizsabino** [comment]
Thank you, it works now

**Comment by S-S-X** [comment]
`it.tr`, `pt.tr` & `pt_BR.tr`.
