### ISSUE TITLE
fix set_physics_override usage

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/homedecor_modpack#70]
current uses three params, should use table in homedecor_common
```
homedecor_modpack/homedecor_common/sit.lua:		clicker:set_physics_override(1, 1, 1)
homedecor_modpack/homedecor_common/sit.lua:		clicker:set_physics_override(0, 0, 0)
```

**Comment by Niklp09** [comment]
This code is outcommented, we can just remove it IMO. https://github.com/mt-mods/homedecor_modpack/blob/d400e421cefef866cdec217e4c6c81b1328c8eab/homedecor_common/sit.lua#L3-L33

**Comment by wsor4035** [comment]
ah, not active, so need for this issue
